### ISSUE TITLE
[BUG]: Cursor text is not visible

### ISSUE THREAD

**Issue by wxh06** [cdalvaro/github-vscode-theme-iterm#15]
### Description of the bug

`Cursor` and `Cursor text` have the same color.

![截屏2024-05-22 23.25.09.png](https://github.com/cdalvaro/github-vscode-theme-iterm/assets/29367025/476928fc-973a-4023-b286-f51b1e245d46)

### Steps To Reproduce

1. Set theme to `GitHub Dark Default`, `GitHub Dark Dimmed` or `GitHub Dark High Contrast`.
2. Enter any character in the shell.
3. Press <kbd>←</kbd> (left arrow).
4. The character is no longer visible.

### Additional Information

The cursor text can be clearly seen in VS Code.

![截屏2024-05-22 23.43.13.png](https://github.com/cdalvaro/github-vscode-theme-iterm/assets/29367025/766638dd-e979-4c0f-bd96-7712d81177c0)

**Comment by cdalvaro** [comment]
Hi @wxh06, thank you for opening this issue! I'll fix it asap!

**Comment by cdalvaro** [comment]
Hi, @wxh06 I'm really sorry for the delay. I hope to fix this soon 😥

In the meantime, you can check the _Smart box cursor color_ in _Settings > Profiles > Colors_ bellow the **Cursors Colors** section:

![Screenshot 2024-06-05 at 10 23 36](https://github.com/cdalvaro/github-vscode-theme-iterm/assets/16347742/43f20a12-d5bb-4fbc-808e-59967d6cb16e)

**Comment by cdalvaro** [comment]
Fixed in:

- [GitHub Dark Default](https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/GitHub%20Dark%20Default.itermcolors) (4c60568d4a8bfbfc681511a249c3d57edb74420b)
- [GitHub Dark Dimmed](https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/GitHub%20Dark%20Dimmed.itermcolors) (94d8e757f188c27dd2acc2806f0b941f7eb3a9bf)
- [GitHub Dark High Contrast](https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/GitHub%20Dark%20High%20Contrast.itermcolors) (2bed993eeee868b729b82a5c88a920667859c742)
- [GitHub Light Default](https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/GitHub%20Light%20Default.itermcolors) (b9a4f10562beb3e7b9c79a3ae8a3f7eac5ea4c8b)
- [GitHub Light High Contrast](https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/GitHub%20Light%20High%20Contrast.itermcolors) (6e414d6c8fae2f1f2c244b3a720c98bdd93f3ac0)

Please @wxh06, close the issue if you consider the issue is solved. Thank you!

**Comment by wxh06** [comment]
Do you plan to update the legacy themes? I love the legacy GitHub Dark

**Comment by cdalvaro** [comment]
Legacy color themes updated too!

- [GitHub Dark Legacy](https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/legacy/GitHub%20Dark.itermcolors) (0de98dfd13095136e2f4880a2c4afb44485ba5e4)
- [GitHub Light Legacy](https://github.com/cdalvaro/github-vscode-theme-iterm/blob/main/legacy/GitHub%20Light.itermcolors) (79a7e6b4e61c6102bb6ff5fe594406b21028175c)

I also have updated the Terminal.app themes.

**Comment by wxh06** [comment]
LGTM! Thanks!

**Comment by cdalvaro** [comment]
> LGTM! Thanks!

Great! Thank you for reporting this issue!
